# Generated by Django 4.2.1 on 2023-06-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="duties",
            field=models.TextField(blank=True, null=True),
        ),
    ]
