# Generated by Django 4.2.1 on 2023-06-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0003_position_duties"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="task_manager.tasktype"
            ),
        ),
    ]
