# Generated by Django 4.2.1 on 2023-06-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0004_worker_cover_alter_task_task_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worker",
            old_name="cover",
            new_name="photo",
        ),
    ]
