# Generated by Django 4.2.1 on 2023-06-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0006_task_status_alter_worker_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_done", "all tasks"),
                    ("in_progress", "tasks that are being worked on"),
                    ("approved", "completed tasks"),
                ],
                max_length=63,
                null=True,
            ),
        ),
    ]
