# Generated by Django 4.2.1 on 2023-07-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0008_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(),
        ),
    ]
